---
title: "Untitled"
output: html_document
date: "2024-03-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
knitr::opts_chunk$set(echo = TRUE)
# Load the libraries
library(ISLR2)
library(glmnet)
#library(tensorflow)
library(keras)
library(Matrix)
library(readr)
use_python("C:\\Users\\ctlan\\anaconda3\\envs\\KNN")
```

## R Markdown
```{r}
xdata <- data.matrix(NYSE[,c("DJ_return", 'log_volume','log_volatility')])

plot(NYSE$DJ_return,)

xdata <- scale(xdata)

acf(xdata[,"log_volume"])
acf(xdata[,"DJ_return"])


```
```{r}
xdata <- apply(xdata,2,scale)
istrain <- NYSE$train  
```

#lag funciton 
```{r}
#lag funciton 
lagm <- function(x,lag){
  n<-nrow(x)
  pad <- matrix(NA,lag,ncol(x))
  rbind(pad,x[1:(n-lag),])
  }

```


```{r}
arframe <- data.frame(log_volume=xdata[,"log_volume"],L1=lagm(xdata,1),L2=lagm(xdata,2),L3=lagm(xdata,3),L4=lagm(xdata,4),L5=lagm(xdata,5))

```


```{r}
arframe <- arframe[-c(1:5),]
istrain <- istrain[-c(1:5)]
```


```{r}
lmfit <- lm(log_volume~L1.log_volume,data = arframe[istrain,])
pred_lm <- predict(lmfit,arframe[!istrain,])
y_test <- arframe[!istrain, "log_volume"]
1-mean((pred_lm-y_test)^2)/var(y_test)
```
```{r}
n <- nrow(arframe)
xrnn <- data.matrix(arframe[,-1])
xrnn <- array(xrnn,c(n,3,5))
xrnn <- xrnn[,,5:1]

xrnn <- arframe(xrnn,(1,3,2))
```


```{r}
model_rnn <- keras_model_sequential() %>%
  layer_simple_rnn(input_shape=c(5,3),units = 16,dropout = 0.1)%>%
  layer_dense(units = 1)

model_rnn %>%
  compile(loss = 'mse',optimizer = optimizer_adam(),
          metrics = 'mean_absolute_error')

model_rnn %>%
  fit(xrnn[istrain,],arframe$log_volume[istrain],batch_size = 32,epochs = 20,validation_split = 0.1)
```
































